/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apartment.Apartment;

import form.FormApartment;
import form.FormRoom;
import form.FormTenant;
import form.FormTenantRoom;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Gink
 */
public class JFrameApartment extends javax.swing.JFrame {

    /**
     * Creates new form JFrameApartment
     */
    public JFrameApartment() {
        initComponents();
        this.setTitle("โปรแกรมการจัดการอพาร์ทเมนต์");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myDesktop = new javax.swing.JDesktopPane();
        myMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuApartment = new javax.swing.JMenuItem();
        menuTenant = new javax.swing.JMenuItem();
        menuRoom = new javax.swing.JMenuItem();
        menuTenantRoom = new javax.swing.JMenuItem();
        menuExitForm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRentApartment = new javax.swing.JMenuItem();
        menuMainApartment = new javax.swing.JMenuItem();
        menuExitFormManagment = new javax.swing.JMenuItem();
        menuExitReport = new javax.swing.JMenu();
        menuReportNetIncome = new javax.swing.JMenuItem();
        menuReportRoom = new javax.swing.JMenuItem();
        menuReportRentCondition = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout myDesktopLayout = new javax.swing.GroupLayout(myDesktop);
        myDesktop.setLayout(myDesktopLayout);
        myDesktopLayout.setHorizontalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        myDesktopLayout.setVerticalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMenu1.setText("ระบบจัดการข้อมูลพื้นฐาน");

        menuApartment.setText("ข้อมูลอพาร์ทเมนท์");
        menuApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApartmentActionPerformed(evt);
            }
        });
        jMenu1.add(menuApartment);

        menuTenant.setText("ข้อมูลผู้เช่า");
        menuTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTenantActionPerformed(evt);
            }
        });
        jMenu1.add(menuTenant);

        menuRoom.setText("ข้อมูลห้องพัก");
        menuRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRoomActionPerformed(evt);
            }
        });
        jMenu1.add(menuRoom);

        menuTenantRoom.setText("ข้อมูลผู้เช่าห้องพัก");
        menuTenantRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTenantRoomActionPerformed(evt);
            }
        });
        jMenu1.add(menuTenantRoom);

        menuExitForm.setText("ออกจากโปรแกรม");
        menuExitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitFormActionPerformed(evt);
            }
        });
        jMenu1.add(menuExitForm);

        myMenu.add(jMenu1);

        jMenu2.setText("ระบบจัดการอพาร์ทเมนท์");

        menuRentApartment.setText("การเช่าอพาร์ทเมนท์");
        menuRentApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRentApartmentActionPerformed(evt);
            }
        });
        jMenu2.add(menuRentApartment);

        menuMainApartment.setText("การบำรุงรักษาอพาร์ทเมนท์");
        menuMainApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainApartmentActionPerformed(evt);
            }
        });
        jMenu2.add(menuMainApartment);

        menuExitFormManagment.setText("ออกจากโปรแกรม");
        menuExitFormManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitFormManagmentActionPerformed(evt);
            }
        });
        jMenu2.add(menuExitFormManagment);

        myMenu.add(jMenu2);

        menuExitReport.setText("ระบบแสดงรายงาน");

        menuReportNetIncome.setText("รายงานแสดงรายได้สุทธิ");
        menuReportNetIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportNetIncomeActionPerformed(evt);
            }
        });
        menuExitReport.add(menuReportNetIncome);

        menuReportRoom.setText("รายงานแสดงข้อมูลห้องว่าง");
        menuReportRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportRoomActionPerformed(evt);
            }
        });
        menuExitReport.add(menuReportRoom);

        menuReportRentCondition.setText("รายงานแสดงข้อมูลผู้เช่าตามเงื่อนไข");
        menuReportRentCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportRentConditionActionPerformed(evt);
            }
        });
        menuExitReport.add(menuReportRentCondition);

        jMenuItem12.setText("ออกจากโปรแกรม");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuExitReport.add(jMenuItem12);

        myMenu.add(menuExitReport);

        setJMenuBar(myMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApartmentActionPerformed
        // TODO add your handling code here:
        FormApartment  formApartment = new FormApartment();
        formApartment.setVisible(true);
        myDesktop.add(formApartment);
    }//GEN-LAST:event_menuApartmentActionPerformed

    private void menuRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRoomActionPerformed
        // TODO add your handling code here:
        FormRoom  formRoom = new FormRoom();
        formRoom.setVisible(true);
        myDesktop.add(formRoom);
    }//GEN-LAST:event_menuRoomActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void menuTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTenantActionPerformed
        // TODO add your handling code here:
        FormTenant formTenant= new FormTenant();
        formTenant.setVisible(true);
        myDesktop.add(formTenant);
    }//GEN-LAST:event_menuTenantActionPerformed

    private void menuTenantRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTenantRoomActionPerformed
        // TODO add your handling code here:
        FormTenantRoom formTenantRoom = new FormTenantRoom();
        formTenantRoom.setVisible(true);
        myDesktop.add(formTenantRoom);
    }//GEN-LAST:event_menuTenantRoomActionPerformed

    private void menuRentApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRentApartmentActionPerformed
        
    //    FormRentApartment formRentApartment = new FormRentApartment();
  //      formRentApartment.setVisible(true);
   //     myDesktop.add(formRentApartment);
    }//GEN-LAST:event_menuRentApartmentActionPerformed

    private void menuMainApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainApartmentActionPerformed
        // TODO add your handling code here:
     //   FormMainApartment formMainApartment = new FormMainApartment();
    //    formMainApartment.setVisible(true);
     //   myDesktop.add(formMainApartment);
    }//GEN-LAST:event_menuMainApartmentActionPerformed

    private void menuReportNetIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportNetIncomeActionPerformed
        // TODO add your handling code here:
//        ReportNetIncome reportNetIncome= new ReportNetIncome();
//        reportNetIncome.setVisible(true);
//        myDesktop.add(reportNetIncome);
    }//GEN-LAST:event_menuReportNetIncomeActionPerformed

    private void menuReportRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportRoomActionPerformed
        // TODO add your handling code here:
//        ReportRoom reportRoom = new ReportRoom();
//        reportRoom.setVisible(true);
//        myDesktop.add(reportRoom);
    }//GEN-LAST:event_menuReportRoomActionPerformed

    private void menuReportRentConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportRentConditionActionPerformed
        // TODO add your handling code here:
//        ReportRentCondition reportRentCondition = new ReportRentCondition();
//        reportRentCondition.setVisible(true);
//       myDesktop.add(reportRentCondition);
    }//GEN-LAST:event_menuReportRentConditionActionPerformed

    private void menuExitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitFormActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"ยืนยันการปิดโปรแกรม","ยืนยัน",
                JOptionPane.YES_NO_CANCEL_OPTION)== JOptionPane.YES_NO_OPTION)
        {System.exit(0);}
    }//GEN-LAST:event_menuExitFormActionPerformed

    private void menuExitFormManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitFormManagmentActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this,"ยืนยันการปิดโปรแกรม","ยืนยัน",
                JOptionPane.YES_NO_CANCEL_OPTION)== JOptionPane.YES_NO_OPTION)
        {System.exit(0);}
    }//GEN-LAST:event_menuExitFormManagmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        MyConnect.getConnection();
        System.out.println("ok");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
//                Font f = new Font("Tahoma", Font.PLAIN, 12);
// 
//            java.util.Enumeration keys = javax.swing.UIManager.getDefaults().keys();
//            while (keys.hasMoreElements()) {
//                Object key = keys.nextElement();
//                Object value = javax.swing.UIManager.get(key);
//                if (value != null && value instanceof java.awt.Font) {
//                    javax.swing.UIManager.put(key, f);
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameApartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem menuApartment;
    private javax.swing.JMenuItem menuExitForm;
    private javax.swing.JMenuItem menuExitFormManagment;
    private javax.swing.JMenu menuExitReport;
    private javax.swing.JMenuItem menuMainApartment;
    private javax.swing.JMenuItem menuRentApartment;
    private javax.swing.JMenuItem menuReportNetIncome;
    private javax.swing.JMenuItem menuReportRentCondition;
    private javax.swing.JMenuItem menuReportRoom;
    private javax.swing.JMenuItem menuRoom;
    private javax.swing.JMenuItem menuTenant;
    private javax.swing.JMenuItem menuTenantRoom;
    private javax.swing.JDesktopPane myDesktop;
    private javax.swing.JMenuBar myMenu;
    // End of variables declaration//GEN-END:variables
}
